spring.application.name=backend


# ==============================
# CONEXIÓN CON POSTGRESQL
# ==============================

# Aquí indicamos la base de datos que utilizará el backend.
# Entonces, Spring se conectará a la base local tasks_db por el puerto 5432.
spring.datasource.url=jdbc:postgresql://localhost:5432/tasks_db

# Aquí indicamos el usuario con el que PostgreSQL permite la conexión.
spring.datasource.username=postgres

# Aquí no escribimos directamente la contraseña.
# Entonces, Spring la toma desde la variable de entorno DB_PASSWORD
# y evitamos subir una credencial real al repositorio.
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# ==============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==============================

# Aquí usamos "update" para que Hibernate cree o actualice
# las tablas necesarias sin borrar los registros existentes.
spring.jpa.hibernate.ddl-auto=update

# Aquí pedimos que las consultas SQL se muestren en consola.
# Entonces podemos observar qué operaciones realiza Hibernate.
spring.jpa.show-sql=true

# Aquí hacemos que esas consultas SQL se impriman de forma ordenada
# para facilitar su lectura durante las pruebas.
spring.jpa.properties.hibernate.format_sql=true